# Generated by Django 5.2.5 on 2025-08-21 00:50

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('stage', models.CharField(choices=[('GRADE6', 'سادس ابتدائي'), ('PREP', 'إعدادي')], max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(django.db.models.functions.text.Lower('email'), name='idx_student_email_ci'), models.Index(models.F('phone'), name='idx_student_phone')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='unique_student_email_ci')],
            },
        ),
    ]
