# Generated by Django 5.2.5 on 2025-08-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('capacity', models.PositiveIntegerField()),
                ('schedule', models.CharField(max_length=100)),
                ('students', models.ManyToManyField(blank=True, related_name='groups', to='students.student')),
            ],
        ),
    ]
