# Generated by Django 5.2.5 on 2025-08-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='days',
            field=models.CharField(blank=True, help_text='اكتب مواعيد المجموعة مثل: سبت، تلات', max_length=100),
        ),
    ]
